### ISSUE TITLE
Unknown Method – yii\base\UnknownMethodException

### ISSUE THREAD

**Issue by CreateSean** [vardump-de/recentchanges#4]
Craft 

When I add a recent changes widget the dashboard is broken with twig errors. The only way to remove it is to disable or uninstall the plugin

```
yii\base\UnknownMethodException: Calling unknown method: craft\web\Application::getSections() in /var/www/html/vendor/yiisoft/yii2/base/Component.php:308
Stack trace:
#0 /var/www/html/vendor/vardump/recentchanges/src/widgets/RecentchangesWidget.php(227): yii\base\Component->__call('getSections', Array)
#1 /var/www/html/vendor/vardump/recentchanges/src/widgets/RecentchangesWidget.php(196): vardump\recentchanges\widgets\RecentchangesWidget->_getEditableSectionIds()
#2 /var/www/html/vendor/vardump/recentchanges/src/widgets/RecentchangesWidget.php(170): vardump\recentchanges\widgets\RecentchangesWidget->_getEntries()
#3 /var/www/html/vendor/craftcms/cms/src/controllers/DashboardController.php(466): vardump\recentchanges\widgets\RecentchangesWidget->getBodyHtml()
#4 /var/www/html/vendor/craftcms/cms/src/controllers/DashboardController.php(104): craft\controllers\DashboardController->_getWidgetInfo(Object(vardump\recentchanges\widgets\RecentchangesWidget))
#5 [internal function]: craft\controllers\DashboardController->actionIndex()
#6 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#7 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#8 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('index', Array)
#9 /var/www/html/vendor/craftcms/cms/src/web/Application.php(350): yii\base\Module->runAction('dashboard/index', Array)
#10 /var/www/html/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('dashboard/index', Array)
#11 /var/www/html/vendor/craftcms/cms/src/web/Application.php(318): yii\web\Application->handleRequest(Object(craft\web\Request))
#12 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#13 /var/www/html/public/index.php(12): yii\base\Application->run()
#14 {main}```

**Comment by rmdev** [comment]
Hi, 
i just released a new version. Should be fixed now.
